### Get all products
GET http://localhost:8080/products

###Get a product
GET http://localhost:8080/products/6701fe7ae2bc7ad5ba9e6f22


###Creat a product
POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
    "productName" : "Caja Christmas",
    "productCost" : 50
}


###Update a product
PUT http://localhost:8080/products/67021aa7988af6772a955307
Content-Type: application/json

{
    "productName" : "Christmas Box",
    "productCost" : 50
}


### Delete a product
DELETE http://localhost:8080/products/67021aa7988af6772a955307